### ISSUE TITLE
anomalyzer_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#10]
```
EEEEEEEEEEE
======================================================================
ERROR: testAddAll (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 168, in testAddAll
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testAddBeginning (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 64, in testAddBeginning
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testAddEnd (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 116, in testAddEnd
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testAddMiddle (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 90, in testAddMiddle
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testAddSingle (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 142, in testAddSingle
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testCopyAllExplicit (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 258, in testCopyAllExplicit
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testCopyAllImplicit (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 226, in testCopyAllImplicit
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testCopyBeginning (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 286, in testCopyBeginning
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testCopyOneRow (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 313, in testCopyOneRow
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testSample (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 330, in testSample
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

======================================================================
ERROR: testScale (__main__.AnomalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "anomalyzer_test.py", line 194, in testScale
    inputFile = FileRecordStream("input_path")
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in __init__
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\file_record_stream.py", line 219, in <listcomp>
    for attrs in zip(names, types, specials)]
  File "D:\nupic\src\python\python3\nupic\data\field_meta.py", line 75, in __init__
    super(FieldMetaInfo, self).__init__(name, type, special)
TypeError: object.__init__() takes no parameters

----------------------------------------------------------------------
Ran 11 tests in 0.007s

FAILED (errors=11)

```

**Comment by chhenning** [comment]
same for file_record_stream_test.py

**Comment by chhenning** [comment]
same for record_stream.py

**Comment by chhenning** [comment]
This might be the solution:
https://stackoverflow.com/questions/48853916/subclassing-from-namedtuple
