### ISSUE TITLE
adaptivescalar_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#13]
```
E.EEs.E
======================================================================
ERROR: testFillHoles (__main__.AdaptiveScalarTest)
Make sure we can fill in holes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 114, in testFillHoles
    decoded = l.decode(numpy.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]))
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 483, in decode
    for i in range(maxZerosInARow):
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: testNonPeriodicEncoderMinMaxNotSpec (__main__.AdaptiveScalarTest)
Non-periodic encoder, min and max not specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 150, in testNonPeriodicEncoderMinMaxNotSpec
    _verify(1, [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
  File "adaptivescalar_test.py", line 140, in _verify
    l.encode(v),
  File "D:\nupic\src\python\python3\nupic\encoders\base.py", line 150, in encode
    self.encodeIntoArray(inputData, output)
  File "D:\nupic\src\python\python3\nupic\encoders\adaptive_scalar.py", line 175, in encodeIntoArray
    super(AdaptiveScalarEncoder, self).encodeIntoArray(input, output)
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 451, in encodeIntoArray
    output[minbin:maxbin + 1] = 1
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: testNonPeriodicEncoderMinMaxSpec (__main__.AdaptiveScalarTest)
Non-periodic encoder, min and max specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 64, in testNonPeriodicEncoderMinMaxSpec
    self._l.encode(1),
  File "D:\nupic\src\python\python3\nupic\encoders\base.py", line 150, in encode
    self.encodeIntoArray(inputData, output)
  File "D:\nupic\src\python\python3\nupic\encoders\adaptive_scalar.py", line 175, in encodeIntoArray
    super(AdaptiveScalarEncoder, self).encodeIntoArray(input, output)
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 451, in encodeIntoArray
    output[minbin:maxbin + 1] = 1
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: testTopDownDecode (__main__.AdaptiveScalarTest)
Test the input description generation and topDown decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 83, in testTopDownDecode
    output = l.encode(v)
  File "D:\nupic\src\python\python3\nupic\encoders\base.py", line 150, in encode
    self.encodeIntoArray(inputData, output)
  File "D:\nupic\src\python\python3\nupic\encoders\adaptive_scalar.py", line 175, in encodeIntoArray
    super(AdaptiveScalarEncoder, self).encodeIntoArray(input, output)
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 451, in encodeIntoArray
    output[minbin:maxbin + 1] = 1
TypeError: slice indices must be integers or None or have an __index__ method

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (errors=4, skipped=1)
```

**Comment by chhenning** [comment]
same with category_test.py

**Comment by chhenning** [comment]
```
..E.s.E
======================================================================
ERROR: testNonPeriodicEncoderMinMaxNotSpec (__main__.AdaptiveScalarTest)
Non-periodic encoder, min and max not specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 150, in testNonPeriodicEncoderMinMaxNotSpec
    _verify(1, [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
  File "adaptivescalar_test.py", line 143, in _verify
    abs(l.getBucketInfo(l.getBucketIndices(v))[0].value - expV),
  File "D:\nupic\src\python\python3\nupic\encoders\adaptive_scalar.py", line 186, in getBucketInfo
    return super(AdaptiveScalarEncoder, self).getBucketInfo(buckets)
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 659, in getBucketInfo
    encoding = self._topDownMappingM.getRow(category)
TypeError: getRow(): incompatible function arguments. The following argument types are supported:
    1. (self: nupic.bindings.math.SM32, arg0: int) -> numpy.ndarray[float32]

Invoked with: <nupic.bindings.math.SM32 object at 0x00000158698C42D0>, 0.0

======================================================================
ERROR: testTopDownDecode (__main__.AdaptiveScalarTest)
Test the input description generation and topDown decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 96, in testTopDownDecode
    topDown = l.topDownCompute(output)[0]
  File "D:\nupic\src\python\python3\nupic\encoders\adaptive_scalar.py", line 197, in topDownCompute
    return super(AdaptiveScalarEncoder, self).topDownCompute(encoded)
  File "D:\nupic\src\python\python3\nupic\encoders\scalar.py", line 679, in topDownCompute
    category = topDownMappingM.rightVecProd(encoded).argmax()
AttributeError: 'nupic.bindings.math.SM32' object has no attribute 'rightVecProd'

----------------------------------------------------------------------
Ran 7 tests in 0.027s

FAILED (errors=2, skipped=1)
```

**Comment by chhenning** [comment]
The original python errors have been resolved by adding int(float value).

**Comment by chhenning** [comment]
```
 encoding = self._topDownMappingM.getRow(category)
TypeError: getRow(): incompatible function arguments. The following argument types are supported:
    1. (self: nupic.bindings.math.SM32, arg0: int) -> numpy.ndarray[float32]
```
encoding = self._topDownMappingM.getRow(category)
to
encoding = self._topDownMappingM.getRow(int(category))

**Comment by chhenning** [comment]
Previous error is fixed. Now we have:
```

D:\nupic\src\python\python3\tests\unit\nupic\encoders>python adaptivescalar_test.py
....s.F
======================================================================
FAIL: testTopDownDecode (__main__.AdaptiveScalarTest)
Test the input description generation and topDown decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adaptivescalar_test.py", line 94, in testTopDownDecode
    self.assertLess(abs(rangeMin - v), l.resolution)
AssertionError: 1.0 not less than 1.0

----------------------------------------------------------------------
Ran 7 tests in 0.010s

FAILED (failures=1, skipped=1)
```

**Comment by chhenning** [comment]
It was an integer division issue.
