### ISSUE TITLE
coordinate_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#14]
```
EEEEEEEEE.....Es.
======================================================================
ERROR: testBitForCoordinate (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 99, in testBitForCoordinate
    b1 = self.encoder._bitForCoordinate(np.array([2, 5, 10]), n)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 180, in _bitForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeAdjacentPositions (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 267, in testEncodeAdjacentPositions
    num=1)
  File "coordinate_test.py", line 344, in overlapsForRelativeAreas
    outputA = encode(encoder, np.array(initPosition), initRadius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeIntoArray (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 171, in testEncodeIntoArray
    output1 = encode(encoder, coordinate, radius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeRelativePositions (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 199, in testEncodeRelativePositions
    num=5)
  File "coordinate_test.py", line 344, in overlapsForRelativeAreas
    outputA = encode(encoder, np.array(initPosition), initRadius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeRelativePositionsAndRadii (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 222, in testEncodeRelativePositionsAndRadii
    num=5)
  File "coordinate_test.py", line 344, in overlapsForRelativeAreas
    outputA = encode(encoder, np.array(initPosition), initRadius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeRelativeRadii (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 207, in testEncodeRelativeRadii
    num=5)
  File "coordinate_test.py", line 344, in overlapsForRelativeAreas
    outputA = encode(encoder, np.array(initPosition), initRadius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeSaturateArea (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 189, in testEncodeSaturateArea
    outputA = encode(encoder, np.array([0, 0]), 2)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testEncodeUnrelatedAreas (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 234, in testEncodeUnrelatedAreas
    overlaps = overlapsForUnrelatedAreas(1499, 37, 5)
  File "coordinate_test.py", line 371, in overlapsForUnrelatedAreas
    num=repetitions, verbose=verbose)
  File "coordinate_test.py", line 344, in overlapsForRelativeAreas
    outputA = encode(encoder, np.array(initPosition), initRadius)
  File "coordinate_test.py", line 318, in encode
    encoder.encodeIntoArray((coordinate, radius), output)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 107, in encodeIntoArray
    winners = self._topWCoordinates(neighbors, self.w)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in _topWCoordinates
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 143, in <listcomp>
    for c in coordinates.tolist()])
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testHashCoordinate (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 78, in testHashCoordinate
    h1 = self.encoder._hashCoordinate(np.array([0]))
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

======================================================================
ERROR: testOrderForCoordinate (__main__.CoordinateEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coordinate_test.py", line 85, in testOrderForCoordinate
    h1 = self.encoder._orderForCoordinate(np.array([2, 5, 10]))
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 166, in _orderForCoordinate
    seed = cls._hashCoordinate(coordinate)
  File "D:\nupic\src\python\python3\nupic\encoders\coordinate.py", line 153, in _hashCoordinate
    hash = int(int(hashlib.md5(coordinateStr).hexdigest(), 16) % (2 ** 64))
TypeError: Unicode-objects must be encoded before hashing

----------------------------------------------------------------------
Ran 17 tests in 0.006s

FAILED (errors=10, skipped=1)
```

**Comment by chhenning** [comment]
Fixed by encoding a string as utf-8

e.g:
hash = int(int(hashlib.md5(coordinateStr.encode('utf-8')).hexdigest(), 16) % (2 ** 64))
