### ISSUE TITLE
logenc_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#18]
```
...F.s
======================================================================
FAIL: testLogEncoder (__main__.LogEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "logenc_test.py", line 107, in testLogEncoder
    self.assertTrue(numpy.array_equal(ranges[0], [1, 1]))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.015s
```

**Comment by chhenning** [comment]
Same for multi_test.py

**Comment by chhenning** [comment]
Similar for random_distributed_scalar_test.py
```
.........New seed generated as: 73305 called by run line 605 -> testOverlapStatistics
..F..s
======================================================================
FAIL: testResolution (__main__.RandomDistributedScalarEncoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "random_distributed_scalar_test.py", line 162, in testResolution
    "Numbers outside resolution have the same encoding")
AssertionError: 400 == 400 : Numbers outside resolution have the same encoding

----------------------------------------------------------------------
Ran 15 tests in 2.509s

FAILED (failures=1, skipped=1)
```

**Comment by chhenning** [comment]
Similar for scalar_test.py
```
...F...Fs....
======================================================================
FAIL: testDecodeAndResolution (__main__.ScalarEncoderTest)
Test the input description generation, top-down compute, and bucket
----------------------------------------------------------------------
Traceback (most recent call last):
  File "scalar_test.py", line 181, in testDecodeAndResolution
    self.assertTrue(numpy.array_equal(ranges[0], [7.5, 7.5]))
AssertionError: False is not true

======================================================================
FAIL: testNonPeriodicBottomUp (__main__.ScalarEncoderTest)
Test Non-periodic encoder bottom-up
----------------------------------------------------------------------
Traceback (most recent call last):
  File "scalar_test.py", line 272, in testNonPeriodicBottomUp
    self.assertLess(abs(rangeMin - v), l.resolution)
AssertionError: 1.0 not less than 1.0

----------------------------------------------------------------------
Ran 13 tests in 0.034s

FAILED (failures=2, skipped=1)
```
