### ISSUE TITLE
knn_classifier_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#2]
There are a bunch of python related exceptions. 
```
d:\nupic\src\python\python3\tests\unit\nupic\algorithms>python knn_classifier_test.py
EEEE.EEE.sE.s
======================================================================
ERROR: testDistanceMetrics (__main__.KNNClassifierTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "knn_classifier_test.py", line 92, in testDistanceMetrics
    _, _, dist, _ = classifier.infer(input)
  File "D:\nupic\src\python\python3\nupic\algorithms\knn_classifier.py", line 714, in infer
    dist = self._getDistances(inputPattern, partitionId=partitionId)
  File "D:\nupic\src\python\python3\nupic\algorithms\knn_classifier.py", line 1012, in _getDistances
    dist = self._calcDistance(sparseInput)
  File "D:\nupic\src\python\python3\nupic\algorithms\knn_classifier.py", line 973, in _calcDistance
    distMax = dist.max()
  File "C:\Python36\lib\site-packages\numpy\core\_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

======================================================================
ERROR: testGetPartitionId (__main__.KNNClassifierTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "knn_classifier_test.py", line 330, in testGetPartitionId
    cat, _, _, _ = classifier.infer(denseA, partitionId=213)
  File "D:\nupic\src\python\python3\nupic\algorithms\knn_classifier.py", line 714, in infer
    dist = self._getDistances(inputPattern, partitionId=partitionId)
  File "D:\nupic\src\python\python3\nupic\algorithms\knn_classifier.py", line 1019, in _getDistances
    dist[self._partitionIdMap.get(partitionId, [])] = numpy.inf
IndexError: index 1 is out of bounds for axis 0 with size 0
```

**Comment by chhenning** [comment]
Here is my understanding. In test "testDistanceMetrics" we create a
    classifier = KNNClassifier(distanceMethod="norm", distanceNorm=2.0)

**Comment by chhenning** [comment]
Testing with nupic using python 2.7 it turns out that the line:
``` classifier.learn(protoA, 0, isSparse=dimensionality)
would create some _Memory of type 
nupic.bindings.math._NearestNeighbor32; proxy of <Swig Object of type 'nupic::NearestNeighbor< nupic::SparseMatrix< nupic::UInt32,nupic::Real32,nupic::Int32,nupic::Real64,nupic::DistanceToZero< nupic::Real32 > > > *

**Comment by chhenning** [comment]
The problem was with the lambda interface. SpareMatrix was not a reference but a value type.

correct ` [](SparseMatrix32_t& self,...`

incorrect `[](SparseMatrix32_t self,...`
