### ISSUE TITLE
nupic.engine.__init__.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#20]
```
EsEsE
======================================================================
ERROR: testPhases (__main__.NetworkSugarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "syntactic_sugar_test.py", line 33, in testPhases
    n = net.Network()
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 609, in __init__
    obj.__func__.__doc__ = docString
AttributeError: attribute '__doc__' of 'builtin_function_or_method' objects is not writable

======================================================================
ERROR: testRegionCollection (__main__.NetworkSugarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "syntactic_sugar_test.py", line 63, in testRegionCollection
    n = net.Network()
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 609, in __init__
    obj.__func__.__doc__ = docString
AttributeError: attribute '__doc__' of 'builtin_function_or_method' objects is not writable
```

**Comment by chhenning** [comment]
Commented out the code for now.

**Comment by chhenning** [comment]
```
EsEs.
======================================================================
ERROR: testPhases (__main__.NetworkSugarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "syntactic_sugar_test.py", line 39, in testPhases
    _r1 = n.addRegion('r1', 'TestNode', '')
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 642, in addRegion
    return self._getRegions()[name]
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 259, in __getitem__
    value = self.valueWrapper(key, value)
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 630, in makeRegion
    r = Region(r, self)
  File "D:\nupic\src\python\python3\nupic\support\lock_attributes.py", line 65, in decorated
    f(self, *args, **kw)
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 406, in __init__
    self._paramTypeCache = {}
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 419, in __setattr__
    setattr(self._region, name, value)
AttributeError: 'nupic.bindings.engine_internal.Region' object has no attribute '_paramTypeCache'

======================================================================
ERROR: testRegionCollection (__main__.NetworkSugarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "syntactic_sugar_test.py", line 68, in testRegionCollection
    r1 = n.addRegion('r1', 'TestNode', '')
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 642, in addRegion
    return self._getRegions()[name]
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 259, in __getitem__
    value = self.valueWrapper(key, value)
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 630, in makeRegion
    r = Region(r, self)
  File "D:\nupic\src\python\python3\nupic\support\lock_attributes.py", line 65, in decorated
    f(self, *args, **kw)
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 406, in __init__
    self._paramTypeCache = {}
  File "D:\nupic\src\python\python3\nupic\engine\__init__.py", line 419, in __setattr__
    setattr(self._region, name, value)
AttributeError: 'nupic.bindings.engine_internal.Region' object has no attribute '_paramTypeCache'
```
