### ISSUE TITLE
sp_overlap_test.py

### ISSUE THREAD

**Issue by chhenning** [chhenning/nupic#7]
```
Running SP overlap test...
scalar encoder, Random seed: 42 and 90 colors
Es
Running SP overlap test...
category encoder, Random seed: 42 and 90 colors
Es
======================================================================
ERROR: testCategory (__main__.TestSPFrequency)
Test that the most frequent possible option is chosen for a scalar
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sp_overlap_test.py", line 57, in testCategory
    self.frequency(n=100, w=21, seed=SEED, numColors=90, encoder = 'scalar')
  File "sp_overlap_test.py", line 116, in frequency
    globalInhibition=True,
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. nupic.bindings.algorithms.SpatialPooler()
    2. nupic.bindings.algorithms.SpatialPooler(inputDimensions: List[int], columnDimensions: List[int], potentialRadius: int=16, potentialPct: float=0.5, globalInhibition: bool=False, localAreaDensity: float=-1.0, numActiveColumnsPerInhArea: int=10.0, stimulusThreshold: int=0, synPermInactiveDec: float=0.01, synPermActiveInc: float=0.1, synPermConnected: float=0.1, minPctOverlapDutyCycles: float=0.001, dutyCyclePeriod: int=1000, boostStrength: float=0.0, seed: int=-1, spVerbosity: int=0, wrapAround: bool=True)

Invoked with: kwargs: columnDimensions=(2048, 1), inputDimensions=(1, 100), potentialRadius=50.0, numActiveColumnsPerInhArea=40, spVerbosity=0, stimulusThreshold=0, potentialPct=0.5, seed=1, globalInhibition=True

======================================================================
ERROR: testScalar (__main__.TestSPFrequency)
Test that the most frequent possible option is chosen for a category
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sp_overlap_test.py", line 63, in testScalar
    self.frequency(n=30, w=21, seed=SEED, numColors=90, encoder = 'category')
  File "sp_overlap_test.py", line 116, in frequency
    globalInhibition=True,
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. nupic.bindings.algorithms.SpatialPooler()
    2. nupic.bindings.algorithms.SpatialPooler(inputDimensions: List[int], columnDimensions: List[int], potentialRadius: int=16, potentialPct: float=0.5, globalInhibition: bool=False, localAreaDensity: float=-1.0, numActiveColumnsPerInhArea: int=10.0, stimulusThreshold: int=0, synPermInactiveDec: float=0.01, synPermActiveInc: float=0.1, synPermConnected: float=0.1, minPctOverlapDutyCycles: float=0.001, dutyCyclePeriod: int=1000, boostStrength: float=0.0, seed: int=-1, spVerbosity: int=0, wrapAround: bool=True)

Invoked with: kwargs: columnDimensions=(2048, 1), inputDimensions=(1, 30), potentialRadius=15.0, numActiveColumnsPerInhArea=40, spVerbosity=0, stimulusThreshold=0, potentialPct=0.5, seed=1, globalInhibition=True

----------------------------------------------------------------------
Ran 4 tests in 0.004s

FAILED (errors=2, skipped=2)
```

**Comment by chhenning** [comment]
potentialRadius needs a unsigned int and not a float. Hence we need to use integer division `potentialRadius=n//2,` in the constructor.
